CFLAGS=-g # -g = debug, -O2 for optimized code CXXFLAGS for g++
CC=gcc-your-favorite-version

linker: linker.cpp
# g++ -g linker.cpp -o linker
$(CC) $(CFLAGS) -o linker linker.cpp
clean:
rm -f linker *~
